---
blank_issues_enabled: false
contact_links:
  - name: JSAndTSMasteryLibrary.com Community Support
    url: https://github.com/MasteryEducation/JSAndTSMasteryLibrary.com/discussions
    about: Please ask and answer questions here.
